import { ApiActionDef } from '../../shared/types';

export const serviceActions: Record<string, ApiActionDef> = {
  'getServiceInfo': { path: '/host/list', method: 'GET' },
  'searchHost': { path: '/host/list', method: 'GET' },
  'getHostDetail': { path: '/clients_services', method: 'GET' },
  'getServiceDetail': { path: '/clients_services', method: 'GET' },
  'saveServiceInfo': { path: '/clients_services/info', method: 'POST' },
  'renewService': { path: '/clients_services/host_renew', method: 'GET' },
  'batchRenewService': { path: '/clients_services/host_batch_renew', method: 'POST' },
  'invoicePaid': { path: '/clients_services/apply_credit', method: 'POST' },
  'serviceDetail': { path: '/clients_services', method: 'GET' },
  'updateHostAmount': { path: '/clients_services/info', method: 'POST' },
  'getHostInfo': { path: '/clients_services/info', method: 'GET' },
  'hostRenewPage': { path: '/clients_services/host_renew', method: 'GET' },
  'hostRenew': { path: '/clients_services/host_renew', method: 'POST' },
  'applyCredit': { path: '/clients_services/apply_credit', method: 'POST' },
  'refundPage': { path: '/clients_services/refund_page', method: 'GET' },
  'addCredit': { path: '/credit', method: 'POST' },
  'product/active': { path: '/provision/default', method: 'POST' },
  'provisionCreate': { path: '/provision/default', method: 'POST' },
  'provisionTerminate': { path: '/provision/default', method: 'POST' },
  'hostDelete': { path: '/clients_services/host', method: 'DELETE' },
  'invoiceDelete': { path: '/invoice/delete', method: 'DELETE' },
  'productInvoice': { path: '/user_productinvoice', method: 'GET' },
  'upgradeConfigPage': { path: '/upgrade/upgrade_config_page', method: 'GET' },
  'upgradeConfigCalc': { path: '/upgrade/upgrade_config_post', method: 'POST' },
  'upgradeConfigCheckout': { path: '/upgrade/checkout_config_upgrade', method: 'POST' },
  'adminUpgradeConfig': { path: '/clients_services/upgrade_config', method: 'POST' },
};
